version: '2'
services:
  ftp_server:
    image: 'emalderson/ftplab:ftp_1.0'
    stdin_open: true
    tty: true
    ports:
      - '21:21'
    networks:
      network_0:
        ipv4_address: 193.20.1.2
  tftp_server:
    image: 'emalderson/ftplab:tftp_1.0'
    stdin_open: true
    tty: true
    ports:
      - '69:69'
    networks:
      network_0:
        ipv4_address: 193.20.1.3
  element_0:
    image: 'sharelatex/sharelatex-full:latest'
    stdin_open: true
    tty: true
networks:
  network_0:
    ipam:
      config:
        - subnet: 193.20.1.1/24
