version: '2'
services:
  Kali:
    image: 'dockersecplayground/reflected_xss_cookies:latest'
    stdin_open: true
    tty: true
    networks:
      network_0:
        ipv4_address: 193.20.1.2
networks:
  network_0:
    ipam:
      config:
        - subnet: 193.20.1.1/24
