version: '2'
services:
  telnet:
    image: nsunina/hacking-ssh-server:1.0
    stdin_open: true
    tty: true
  ftp:
    image: nsunina/hacking-ssh-server:1.0
    stdin_open: true
    tty: true
  samba:
    image: nsunina/hacking-ssh-server:1.0
    stdin_open: true
    tty: true
  hacking:
    image: nsunina/hacking-ssh-server:1.0
    stdin_open: true
    tty: true
    ports:
      - '13389:3389'
networks: {}
