version: '2'
services:
  website:
    image: 'nsunina/l00-wiresharklab-website:1.0'
    stdin_open: true
    tty: true
    ports:
      - '8090:80'
    networks:
      wireshark_subnet:
        ipv4_address: 193.21.1.4
  wireshark:
    image: 'nsunina/l00-wiresharklab-wireshark:1.0'
    stdin_open: true
    tty: true
    ports:
      - '14500:14500'
    networks:
      wireshark_subnet:
        ipv4_address: 193.21.1.5
    environment:
      - XPRA_PW=wireshark
    cap_add:
      - NET_ADMIN
networks:
  wireshark_subnet:
    ipam:
      config:
        - subnet: 193.21.1.1/24
