services:
  website:
    image: nsunina/wireshark_website:v1.1
    stdin_open: true
    tty: true
    ports:
      - '8090:80'
    networks:
      wireshark_subnet:
        ipv4_address: 193.21.1.4
    volumes:
      - ./website:/var/www/
    cap_add:
      - NET_ADMIN
    privileged: true
  wireshark:
    image: lscr.io/linuxserver/wireshark:4.6.1
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 14500:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      wireshark_subnet:
        ipv4_address: 193.21.1.5
networks:
  wireshark_subnet:
    ipam:
      config:
        - subnet: 193.21.1.0/24
