version: '2'
services:
  ftp_server:
    image: 'nsunina/ftp-server:1.0'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.4
    cap_add:
      - ALL
  Alice:
    image: 'nsunina/netcat:1.0'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.2
    cap_add:
      - ALL
  Bob:
    image: 'nsunina/netcat:1.0'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.3
    cap_add:
      - ALL
  http_server:
    image: 'nsunina/apache:5.6'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.5
    volumes:
      - './website:/var/www/html'
networks:
  mySubnet:
    ipam:
      config:
        - subnet: 193.20.1.1/24
