version: '2'
services:
  client:
    image: 'nsunina/hacking:1.0'
    stdin_open: true
    tty: true
    ports:
      - '13389:3389'
    networks:
      public_client_network:
        ipv4_address: 193.20.4.4
    cap_add:
      - NET_ADMIN
  ssh_server:
    image: 'nsunina/l08-ssh-portforwarding-ssh-server:1.0'
    stdin_open: true
    tty: true
    ports:
      - '2222:22'
    networks:
      not_visible_network:
        ipv4_address: 193.20.2.2
      public_client_network:
        ipv4_address: 193.20.4.2
    cap_add:
      - NET_ADMIN
  music_server:
    image: 'nsunina/l08-ssh-portforwarding-musicserver:1.0'
    stdin_open: true
    tty: true
    networks:
      not_visible_network:
        ipv4_address: 193.20.2.3
    cap_add:
      - NET_ADMIN
    privileged: true
networks:
  not_visible_network:
    ipam:
      config:
        - subnet: 193.20.2.1/24
  public_client_network:
    ipam:
      config:
        - subnet: 193.20.4.1/24
