FROM dockersecplayground/iplog:v1.0
 LABEL \
       type="host" \
       caps_add="NET_ADMIN" \
       actions.iplog.command="/run_iplog.sh " \ 
       actions.iplog.description="Run iplog in the host" 