version: '2'
services:
  SMPT_server:
    image: 'nsunina/postfix:1.0'
    stdin_open: true
    tty: true
    networks:
      public_network:
        ipv4_address: 193.21.1.3
    cap_add:
      - ALL
  hacking:
    image: 'nsunina/hacking:1.0'
    stdin_open: true
    tty: true
    ports:
      - '13389:3389'
    networks:
      public_network: {}
    cap_add:
      - ALL
networks:
  public_network:
    ipam:
      config:
        - subnet: 193.21.1.1/24
