version: '2'
services:
  Kali:
    image: 'nsunina/hacking:1.0'
    stdin_open: true
    tty: true
    ports:
      - '13389:3389'
    networks:
      internal_network:
        ipv4_address: 192.168.2.3
    environment:
      - GATEWAY=192.168.2.2
  router:
    image: 'dockersecplayground/alpine_router:v1.0'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.2
      telnet_network:
        ipv4_address: 192.168.1.2
    cap_add:
      - ALL
  TelnetServer:
    image: 'dockersecplayground/alpine_telnet:v1.0'
    stdin_open: true
    tty: true
    networks:
      telnet_network:
        ipv4_address: 192.168.1.3
    cap_add:
      - ALL
  telnet_client:
    image: 'nsunina/networking:1.0'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.4
    environment:
      - GATEWAY=192.168.2.2
    cap_add:
      - ALL
  scapy:
    image: 'nsunina/networking:1.0'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.5
    environment:
      - GATEWAY=192.168.2.2
    cap_add:
      - ALL
networks:
  telnet_network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  internal_network:
    ipam:
      config:
        - subnet: 192.168.2.1/24
